# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RACDemo' do

   use_frameworks!

  pod 'ReactiveCocoa', '~> 2.5'
  # Pods for RACDemo

  target 'RACDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RACDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
